menu:
    Loft: /
    Archive: /archives/
    About: /about/
    Links: /links/
    RSS: /atom.xml

favicon: /favicon.ico
logo: /logo.svg

# Comment
# e.g disqus: seansun
valine:
  enable: true # if you want use valine, please set enable: true
  appid:  N1tTKn3LEO1Xmg4kMyX8TDy6-gzGzoHsz # your leancloud appid
  appkey:  i4xk0BbhpGn2n9OlAelavNx9 # your leancloud appkey
  notify: false # true/false:mail
  verify: false # true/false:verify code
  avatar: retro # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  avatar_cdn: https://sdn.geekzu.org/avatar/
  serverURLs: https://api.iloft.xyz
  placeholder: # comment box placeholder

# Analytics
# google-analytics:
ga: UA-89639365-1

# Copyright Infomation
startyear: 2013

# Styles shoule be found in the list: https://highlightjs.org/static/demo/
# use the lowercase letters and replace space with -
codestyle: Github